name: build
on:
  push:
    branches:
    - "*"
env:
  TERM: xterm-color
jobs:
  pipeline:
    name: Build Pipeline
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 1        
    - name: Build Toolbox image
      run: make build
    - name: Lint shell files
      run: make shell-lint
