name: workflow
on:
  push:
    branches:
    - "*"
env:
  TERM: xterm-color
  RELEASE_ARCHIVE: target/toolbox.zip
jobs:
  workflow:
    name: Workflow
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 1        
    - name: Build Toolbox image
      run: make build
    - name: Lint shell files
      run: make shell-lint
    - name: Create release
      if: github.ref == "refs/heads/master"
      uses: release-drafter/release-drafter@v5
      with:
        config-name: release-config.yaml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Log into registry
      if: github.ref == "refs/heads/master"      
      run: docker login -u seek --password-stdin <<< "${{ secrets.DOCKER_PASSWORD }}"
    - name: Publish Docker image
      if: github.ref == "refs/heads/master"      
      run: make build push push-latest RELEASE_VERSION=$(echo $GITHUB_REF | cut -d / -f 3)
    - name: Package files
      if: github.ref == "refs/heads/master"      
      run: make package RELEASE_VERSION=$(echo $GITHUB_REF | cut -d / -f 3)
    - name: Upload files
      if: github.ref == "refs/heads/master"      
      uses: alexellis/upload-assets@0.2.2
      with:
        asset_paths: '["${{ env.RELEASE_ARCHIVE }}"]'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
